fixed broken export
rakugoteam/Rakugo-Game-Template pull request #4
Opened 2024-05-23 19:20 UTC by Jeremi360

fixed broken export by moving const/project_settings to RGT_Globals

2024-05-23 21:25 UTC, theludovyc requested changes
Thank you to have handle it 😊

2024-05-23 21:25 UTC, theludovyc commented on .vscode/settings.json
> +{
You should add it in the .gitignore or in your local gitignore .git/info/exclude

2024-05-23 21:35 UTC, theludovyc approved these changes

2024-05-25 13:32 UTC, Jeremi360 commented on .vscode/settings.json
> +{
done I also remove *.tmp files

2024-05-25 13:32 UTC, merged